# ==========================================
# MCP工具分析配置文件 v3.0
# ==========================================
# 说明：该配置文件定义了MCP工具分析的基础配置参数
# 版本：v3.0 - 移除硬编码工具列表，改为从MCP管理器动态获取
# ==========================================

# ==========================================
# 工具分析LLM配置
# ==========================================
llm_analysis:
  # 使用与意图识别相同的配置
  inherit_from_intent_config: true
  
  # LLM分析参数配置
  model_params:
    max_tokens: 500
    temperature: 0.1
    timeout: 30
    max_retries: 2

# ==========================================
# 错误处理配置
# ==========================================
error_handling:
  # 工具不存在时的处理
  tool_not_found:
    message: "抱歉，您请求的操作「{tool_name}」暂不支持。"
    suggestion: "请检查当前可用的MCP工具。"
    
  # 工具被禁用时的处理
  tool_disabled:
    message: "工具「{tool_name}」当前已被禁用。"
    suggestion: "请联系管理员启用此功能。"
    
  # MCP开关关闭时的处理
  mcp_disabled:
    message: "MCP功能当前已关闭，无法执行系统操作。"
    suggestion: "请在页面上打开MCP开关后重试。"

# ==========================================
# 性能配置  
# ==========================================
performance:
  # 工具执行超时时间（秒）
  execution_timeout: 30
  
  # 并发执行配置
  max_concurrent_tools: 3
  
  # 重试配置
  max_retries: 2
  retry_delay: 1

# ==========================================
# 参数提取配置
# ==========================================
parameter_extraction:
  # 文件名提取模式
  file_name_patterns:
    - r'(?:创建|生成|新建).*?([a-zA-Z0-9\u4e00-\u9fff]+\.[a-zA-Z0-9]+)'
    - r'([a-zA-Z0-9\u4e00-\u9fff]+\.[a-zA-Z0-9]+)'
  
  # 文件夹名提取模式
  folder_name_patterns:
    - r'(?:创建|新建).*?([a-zA-Z0-9\u4e00-\u9fff]+)(?:文件夹|目录)'
    - r'([a-zA-Z0-9\u4e00-\u9fff]+)(?:文件夹|目录)'
  
  # 父目录提取模式
  parent_folder_patterns:
    - r'在\s*([a-zA-Z0-9\u4e00-\u9fff]+)\s*(?:文件夹|目录|下)'
    - r'([a-zA-Z0-9\u4e00-\u9fff]+)\s*(?:文件夹|目录)\s*下'

# ==========================================
# 关键词匹配配置
# ==========================================
keyword_matching:
  # 创建操作关键词
  create_keywords:
    - "创建"
    - "新建"
    - "生成"
    - "制作"
  
  # 文件相关关键词
  file_keywords:
    - "文件"
    - ".txt"
    - ".doc"
    - ".pdf"
    - ".md"
    - ".json"
    - ".csv"
    - ".html"
    - ".py"
    - ".js"
  
  # 文件夹相关关键词
  folder_keywords:
    - "文件夹"
    - "目录"
    - "folder"
    - "directory" 